version: '3.9'
services:
  app:
    build:
      context: ./laravel-app
      dockerfile: Dockerfile.dev   
    restart: unless-stopped
    networks:
      - docker-network
    ports:
      - 9000:9000
    volumes:
      - ./laravel-app:/var/www/html
    environment:
      - APP_ENV=local
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  queue-worker:
    build:
      context: ./laravel-app
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    networks:
      - docker-network
    depends_on:
      - db
    volumes:
      - ./laravel-app:/var/www/html
    command: php artisan queue:work

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - app
    networks:
      - docker-network
    ports:
      - 80:80
      - 443:443
    volumes:
      # Monta la carpeta con el c贸digo del proyecto
      - ./laravel-app:/var/www/html
      # Monta tu archivo de configuraci贸n de Nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  # Base de datos
  db:
    image: bitnami/postgresql:16.3.0
    # ...
    # No cambia respecto a tu configuraci贸n original
    networks:
      - docker-network

  # Redis
  redis:
    image: bitnami/redis:7.2
    # ...
    # No cambia respecto a tu configuraci贸n original
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
