# Dockerfile.dev
FROM php:8.3.11-fpm

# Instala dependencias
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg-dev \
    libwebp-dev \
    libxpm-dev \
    libfreetype6-dev \
    libzip-dev \
    zip \
    unzip \
    git \
    bash \
    fcgiwrap \
    libmcrypt-dev \
    libonig-dev \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Extensiones de PHP
RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
    && docker-php-ext-install gd \
    && docker-php-ext-install pdo pdo_pgsql mbstring zip exif pcntl bcmath opcache

# Instala Composer
COPY --from=composer/composer:latest-bin /composer /usr/bin/composer

# OJO: No copies aquí el código para desarrollo
# Manejarás el volumen en docker-compose.

WORKDIR /var/www/html

# Establece el usuario www-data
RUN chown -R www-data:www-data /var/www/html
USER www-data

EXPOSE 9000

CMD ["php-fpm"]
